### ISSUE TITLE
Error: expected file.path to export a function or instance

### ISSUE THREAD

**Issue by rbecheras** [rbecheras/generate-swap-project#6]
The master branch works fine and tests pass on travis AND on local dev host.
Tests are run by the  following yarn script (on master):

```sh
$ yarn test
```

However in the PR #2 (Resolve #1 "Convert to ESNext/StandardJS code style"), I made the following changes:
- converted `ES5` codebase to `ESNext`
- moved codebase to `src/lib` and `src/tests`
- added a `generator.js` file a t root level that just requires `./dist/lib/generator.js`
- added yarn scripts: clear + lint + build + test (cf. [readme section](https://github.com/rbecheras/generate-swap-project/tree/1-convert-to-standard-code-style#discover-the-tasks-pipeline)

Tests are run by the  following yarn script (on branch `1-convert-to-standard-code-style`):

```sh
$ yarn pipeline
```

that is an alias to `yarn clear && yarn lint && yarn build && yarn test`

But now one test fails with a stragy error: `Error: expected file.path to export a function or instance`:

```
$ yarn pipeline
yarn run v1.3.2
$ yarn clear && yarn lint && yarn build && yarn test
$ yarn rimraf build dist
$ /home/remi/d/dev/generate-swap-project/node_modules/.bin/rimraf build dist
$ yarn lint:esnext
$ yarn standard src/*.js src/**/*.js
$ /home/remi/d/dev/generate-swap-project/node_modules/.bin/standard 'src/*.js' src/lib/generator.js src/tests/plugin.js src/tests/test.js
$ yarn build:lib && yarn build:tests && yarn build:docs
$ yarn babel src/lib/ --out-dir dist/lib --source-maps
$ /home/remi/d/dev/generate-swap-project/node_modules/.bin/babel src/lib/ --out-dir dist/lib --source-maps
src/lib/generator.js -> dist/lib/generator.js
$ yarn babel src/tests/ --out-dir dist/tests --source-maps
$ /home/remi/d/dev/generate-swap-project/node_modules/.bin/babel src/tests/ --out-dir dist/tests --source-maps
src/tests/plugin.js -> dist/tests/plugin.js
src/tests/test.js -> dist/tests/test.js
$ echo WARNING: No documentation build available yet
WARNING: No documentation build available yet
$ yarn mocha dist/tests/**/*.js
$ /home/remi/d/dev/generate-swap-project/node_modules/.bin/mocha 'dist/tests/**/*.js'


  generate-swap-project
    plugin
      ✓ should add tasks to the instance (80ms)
      ✓ should only register the plugin once

  generate-swap-project
    tasks
      ✓ should extend tasks onto the instance
      ✓ should run the `default` task with .build (186ms)
      ✓ should run the `default` task with .generate
    swap-project (CLI)
      1) should run the default task using the `generate-swap-project` name (global install)
      ✓ should run the default task using the `swap-project` generator alias (local generator.js)
    swap-project (API)
      ✓ should run the default task on the generator
      ✓ should run the `swap-project` task
      ✓ should run the `default` task when defined explicitly
    sub-generator
      ✓ should work as a sub-generator
      ✓ should run the `default` task by default
      ✓ should run the `generator:default` task when defined explicitly
      ✓ should run the `generator:swap-project` task
      ✓ should work with nested sub-generators
      ✓ should run tasks as a sub-generator


  15 passing (1s)
  1 failing

  1) generate-swap-project
       swap-project (CLI)
         should run the default task using the `generate-swap-project` name (global install):
     Error: expected file.path to export a function or instance
      at Env.get (node_modules/base-env/lib/file.js:256:11)
      at Env.invoke (node_modules/base-env/lib/env.js:117:19)
      at Generate.<anonymous> (node_modules/base-generators/lib/generator.js:62:30)
      at Generate.getGenerator (node_modules/base-generators/index.js:157:22)
      at Object.exports.process (node_modules/base-generators/lib/tasks.js:127:24)
      at node_modules/base-generators/lib/tasks.js:86:23
      at Array.reduce (<anonymous>)
      at exports.parse (node_modules/base-generators/lib/tasks.js:85:15)
      at Generate.generate (node_modules/base-generators/index.js:490:21)
      at Generate.generate (node_modules/base-generators/index.js:463:23)
      at Context.<anonymous> (dist/tests/test.js:87:11)



error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

What's wrong ?

**Comment by doowb** [comment]
This is most likely due to how es6 is transpiled. In your `generator.js` file, you might need to add `.default` after the require statement.

**Comment by rbecheras** [comment]
@doowb thanks for helping me.

The travis build didn't fail because indeed the CLI tests was not run. So the 1 of 15 failing test is just the one skiped by travis.

I just merged new changes in this branch to enable CLI tests in travis builds, and it works (so, now, all the travis jobs fail the same way as on the local dev host)

**Comment by rbecheras** [comment]
> cf. #2 for the resulting error in travis build

**Comment by rbecheras** [comment]
@doowb awesome you rocks, all seems to work as expected now. Travis is running but it looks great!

Thanks!
